In [1]:
# Lab 9 XOR
# Neural Net 적용 (XOR 문제 풀기 위해 layer 추가)
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)  # for reproducibility

x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)

X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

W1 = tf.Variable(tf.random_normal([2, 2]), name='weight1') # out
# 여기서 [2, 2]인 이유: x1과 x2라서 2이고, 출력은 모델러가 정하는데 2로 해본 것
# 인풋: X가 2개구나, 아웃풋: 1번째 layer에서 출력을 2개로 하고 싶어요
b1 = tf.Variable(tf.random_normal([2]), name='bias1')
layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

W2 = tf.Variable(tf.random_normal([2, 1]), name='weight2')
# 여기서 [2, 1]인 이유: 입력은 layer1에서 받아온 것이 2이고, 출력은 1
b2 = tf.Variable(tf.random_normal([1]), name='bias2')
hypothesis = tf.sigmoid(tf.matmul(layer1, W2) + b2) 
# 위 식을 보면 layer1에서 나온 값을 2번째 Layer에 추가

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        _, cost_val = sess.run([train, cost], feed_dict={X: x_data, Y: y_data})
        if step % 100 == 0:
            print(step, cost_val)

    # Accuracy report
    h, p, a = sess.run(
        [hypothesis, predicted, accuracy], feed_dict={X: x_data, Y: y_data}
    )
    
    print(f"\nHypothesis:\n{h} \nPredicted:\n{p} \nAccuracy:\n{a}")


'''
Hypothesis:
[[0.01338216]
 [0.98166394]
 [0.98809403]
 [0.01135799]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0
'''


C:\Users\sds\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


0 0.7584403
100 0.69586563
200 0.69405544
300 0.69245243
400 0.6908216
500 0.688999
600 0.6868359
700 0.6841758
800 0.6808396
900 0.6766206
1000 0.67128885
1100 0.66461027
1200 0.6563796
1300 0.64646435
1400 0.6348422
1500 0.6216097
1600 0.6069378
1700 0.59097785
1800 0.57374084
1900 0.55498725
2000 0.5341575
2100 0.51038074
2200 0.48264128
2300 0.45019028
2400 0.41314086
2500 0.372864
2600 0.3317341
2700 0.2922864
2800 0.25639713
2900 0.22497271
3000 0.19811332
3100 0.17544404
3200 0.15639664
3300 0.14037852
3400 0.12685262
3500 0.11536386
3600 0.105539456
3700 0.09707894
3800 0.089741796
3900 0.08333558
4000 0.07770607
4100 0.072729
4200 0.06830373
4300 0.06434828
4400 0.06079528
4500 0.0575891
4600 0.054683596
4700 0.052040078
4800 0.04962601
4900 0.04741394
5000 0.045380343
5100 0.043505214
5200 0.041771397
5300 0.04016398
5400 0.03866999
5500 0.037278198
5600 0.035978787
5700 0.034763098
5800 0.03362347
5900 0.03255318
6000 0.031546306
6100 0.03059746
6200 0.029701883
6300 0.02885

'\nHypothesis:\n[[0.01338216]\n [0.98166394]\n [0.98809403]\n [0.01135799]] \nPredicted:\n[[0.]\n [1.]\n [1.]\n [0.]] \nAccuracy:\n1.0\n'

In [3]:
# Lab 9 XOR
# Neural Net 적용 (XOR 문제 풀기 위해 layer 추가)
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)  # for reproducibility

x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)

X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

W1 = tf.Variable(tf.random_normal([2, 2]), name='weight1') # out
# 여기서 [2, 2]인 이유: x1과 x2라서 2이고, 출력은 모델러가 정하는데 2로 해본 것
b1 = tf.Variable(tf.random_normal([2]), name='bias1')
layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

W2 = tf.Variable(tf.random_normal([2, 1]), name='weight2')
# 여기서 [2, 1]인 이유: 입력은 layer1에서 받아온 것이 2이고, 출력은 1
b2 = tf.Variable(tf.random_normal([1]), name='bias2')
hypothesis = tf.sigmoid(tf.matmul(layer1, W2) + b2) 
# 위 식을 보면 layer1에서 나온 값을 2번째 Layer에 추가

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
train = tf.train.AdamOptimizer(learning_rate=0.1).minimize(cost) # 수정 # not working better than GradientDescentOptimizer

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer()) ### 

    for step in range(10001):
        _, cost_val = sess.run([train, cost], feed_dict={X: x_data, Y: y_data})
        if step % 100 == 0:
            print(step, cost_val)

    # Accuracy report
    h, p, a = sess.run(
        [hypothesis, predicted, accuracy], feed_dict={X: x_data, Y: y_data}
    )
    
    print(f"\nHypothesis:\n{h} \nPredicted:\n{p} \nAccuracy:\n{a}")


'''
Hypothesis:
[[0.01338216]
 [0.98166394]
 [0.98809403]
 [0.01135799]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0
'''


0 1.0986637
100 0.48266536
200 0.3575529
300 0.35209545
400 0.35004842
500 0.34900552
600 0.3483885
700 0.347988
800 0.34771103
900 0.3475101
1000 0.34735936
1100 0.3472426
1200 0.34715033
1300 0.34707594
1400 0.34701473
1500 0.34696412
1600 0.34692144
1700 0.34688514
1800 0.34685403
1900 0.34682727
2000 0.34680378
2100 0.34678328
2200 0.34676534
2300 0.34674922
2400 0.34673506
2500 0.34672225
2600 0.34671086
2700 0.34670046
2800 0.34669116
2900 0.3466828
3000 0.346675
3100 0.34666795
3200 0.34666157
3300 0.34665558
3400 0.34665036
3500 0.3466453
3600 0.3466407
3700 0.3466366
3800 0.3466326
3900 0.34662908
4000 0.3466256
4100 0.3466225
4200 0.34661958
4300 0.34661683
4400 0.3466143
4500 0.34661198
4600 0.34660983
4700 0.3466077
4800 0.34660578
4900 0.3466039
5000 0.34660232
5100 0.34660062
5200 0.34659928
5300 0.34659773
5400 0.34659642
5500 0.34659517
5600 0.34659404
5700 0.34659293
5800 0.34659186
5900 0.34659094
6000 0.3465901
6100 0.34658906
6200 0.3465883
6300 0.3465876
6400 0.346

'\nHypothesis:\n[[0.01338216]\n [0.98166394]\n [0.98809403]\n [0.01135799]] \nPredicted:\n[[0.]\n [1.]\n [1.]\n [0.]] \nAccuracy:\n1.0\n'

In [4]:
# Lab 9 XOR
# Neural Net 적용 (XOR 문제 풀기 위해 layer 추가)
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)  # for reproducibility

x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)

X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

W1 = tf.Variable(tf.random_normal([2, 2]), name='weight1') # out
# 여기서 [2, 2]인 이유: x1과 x2라서 2이고, 출력은 모델러가 정하는데 2로 해본 것
b1 = tf.Variable(tf.random_normal([2]), name='bias1')
layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

W2 = tf.Variable(tf.random_normal([2, 1]), name='weight2')
# 여기서 [2, 1]인 이유: 입력은 layer1에서 받아온 것이 2이고, 출력은 1
b2 = tf.Variable(tf.random_normal([1]), name='bias2')
hypothesis = tf.sigmoid(tf.matmul(layer1, W2) + b2) 
# 위 식을 보면 layer1에서 나온 값을 2번째 Layer에 추가

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
train = tf.train.AdamOptimizer(learning_rate=0.1).minimize(cost) # 수정 # not working better than GradientDescentOptimizer

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer()) ### ?????

    for step in range(10001):
        _, cost_val = sess.run([train, cost], feed_dict={X: x_data, Y: y_data})
        if step % 100 == 0:
            print(step, cost_val)

    # Accuracy report
    h, p, a = sess.run(
        [hypothesis, predicted, accuracy], feed_dict={X: x_data, Y: y_data}
    )
    
    print(f"\nHypothesis:\n{h} \nPredicted:\n{p} \nAccuracy:\n{a}")


'''
Hypothesis:
[[0.01338216]
 [0.98166394]
 [0.98809403]
 [0.01135799]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0
'''


TypeError: _variable_v1_call() got an unexpected keyword argument 'initializer'

`xavier_intializer` is defined in Xavier Glorot and Yoshua Bengio (2010): Understanding the difficulty of training deep feedforward neural networks. International conference on artificial intelligence and statistics.