In [1]:
# Lab 6 Softmax Classifier
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]] # one-hot encoding # 하나만 hot하다

X = tf.placeholder("float", [None, 4]) # shape에 주의 # 4개의 feature
Y = tf.placeholder("float", [None, 3]) # shape에 주의 # 3개의 label
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight') # 코딩 용이 
b = tf.Variable(tf.random_normal([nb_classes]), name='bias') # 코딩 용이

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b) 

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(2001):
            _, cost_val = sess.run([optimizer, cost], feed_dict={X: x_data, Y: y_data})

            if step % 200 == 0:
                print(step, cost_val)

    print('--------------')
    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))

    print('--------------')
    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))

    print('--------------')
    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))

    print('--------------') # all 에 대한 질문에 대한 답
    all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))

'''
0 6.926112
200 0.6005015
400 0.47295815
600 0.37342924
800 0.28018373
1000 0.23280522
1200 0.21065344
1400 0.19229904
1600 0.17682323
1800 0.16359556
2000 0.15216158
-------------
[[1.3890490e-03 9.9860185e-01 9.0613084e-06]] [1]
-------------
[[0.9311919  0.06290216 0.00590591]] [0]
-------------
[[1.2732815e-08 3.3411323e-04 9.9966586e-01]] [2]
-------------
[[1.3890490e-03 9.9860185e-01 9.0613084e-06]
 [9.3119192e-01 6.2902197e-02 5.9059085e-03]
 [1.2732815e-08 3.3411323e-04 9.9966586e-01]] [1 0 2]
'''


C:\Users\sds\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


0 6.926112
200 0.6005018
400 0.4729582
600 0.37342912
800 0.2801835
1000 0.23280513
1200 0.21065336
1400 0.192299
1600 0.1768232
1800 0.16359553
2000 0.1521616
--------------
[[1.3890432e-03 9.9860197e-01 9.0612402e-06]] [1]
--------------
[[0.93119204 0.06290206 0.00590588]] [0]
--------------
[[1.2732767e-08 3.3411323e-04 9.9966586e-01]] [2]
--------------
[[1.3890432e-03 9.9860197e-01 9.0612402e-06]
 [9.3119204e-01 6.2902056e-02 5.9058843e-03]
 [1.2732767e-08 3.3411323e-04 9.9966586e-01]] [1 0 2]


'\n0 6.926112\n200 0.6005015\n400 0.47295815\n600 0.37342924\n800 0.28018373\n1000 0.23280522\n1200 0.21065344\n1400 0.19229904\n1600 0.17682323\n1800 0.16359556\n2000 0.15216158\n-------------\n[[1.3890490e-03 9.9860185e-01 9.0613084e-06]] [1]\n-------------\n[[0.9311919  0.06290216 0.00590591]] [0]\n-------------\n[[1.2732815e-08 3.3411323e-04 9.9966586e-01]] [2]\n-------------\n[[1.3890490e-03 9.9860185e-01 9.0613084e-06]\n [9.3119192e-01 6.2902197e-02 5.9059085e-03]\n [1.2732815e-08 3.3411323e-04 9.9966586e-01]] [1 0 2]\n'